using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace Echoes.ViewModels;

public partial class IpInfoViewModel : ObservableObject
{
    [ObservableProperty] private string _targetIp = string.Empty;
    [ObservableProperty] private string _rawResult = string.Empty;
    [ObservableProperty] private bool _isWorking;

    [ObservableProperty] private bool _useProxy;
    [ObservableProperty] private string _proxyAddress = string.Empty;
    [ObservableProperty] private string _proxyUser = string.Empty;
    [ObservableProperty] private string _proxyPass = string.Empty;

    private readonly string[] _apiEndpoints =
    {
        "https://ipwho.is/{0}",
        "https://ipapi.co/{0}/json/",
        "http://ip-api.com/json/{0}",
        "https://freeipapi.com/api/json/{0}"
    };

    [RelayCommand]
    private async Task GetMyIp()
    {
        TargetIp = string.Empty;
        await FetchIpInfo(string.Empty);
    }

    [RelayCommand]
    private async Task LookupIp()
    {
        await FetchIpInfo(TargetIp);
    }

    private async Task FetchIpInfo(string ip)
    {
        IsWorking = true;
        RawResult = "Fetching information...";
        var errorLog = new StringBuilder();

        foreach (var endpoint in _apiEndpoints)
        {
            try
            {
                string url = string.Format(endpoint, ip);
                var args = new List<string> { "-s", "-L", "--connect-timeout 5", "-A \"Mozilla/5.0\"" };
                if (UseProxy && !string.IsNullOrWhiteSpace(ProxyAddress))
                {
                    args.Add($"-x \"{ProxyAddress}\"");
                    if (!string.IsNullOrWhiteSpace(ProxyUser) && !string.IsNullOrWhiteSpace(ProxyPass))
                        args.Add($"-U \"{ProxyUser}:{ProxyPass}\"");
                }
                args.Add($"\"{url}\"");

                var psi = new ProcessStartInfo
                {
                    FileName = "curl",
                    Arguments = string.Join(" ", args),
                    UseShellExecute = false,
                    CreateNoWindow = true,
                    RedirectStandardOutput = true
                };

                using var process = Process.Start(psi);
                if (process == null) continue;

                string response = await process.StandardOutput.ReadToEndAsync();
                await process.WaitForExitAsync();

                if (!string.IsNullOrWhiteSpace(response))
                {
                    int firstBrace = response.IndexOf('{');
                    int lastBrace = response.LastIndexOf('}');

                    if (firstBrace != -1 && lastBrace != -1)
                    {
                        string jsonOnly = response.Substring(firstBrace, (lastBrace - firstBrace) + 1);
                        try
                        {
                            using var doc = JsonDocument.Parse(jsonOnly);
                            var sb = new StringBuilder();
                            ParseElement(doc.RootElement, sb, "");

                            sb.AppendLine();
                            sb.AppendLine("--------------------------------------------");
                            sb.AppendLine("Generated by Echoes");

                            RawResult = sb.ToString();
                            IsWorking = false;
                            return;
                        }
                        catch
                        {
                            RawResult = response.Trim() + Environment.NewLine + Environment.NewLine + "Echoes";
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                errorLog.AppendLine($"Error: {ex.Message}");
            }
        }
        RawResult = "Failed." + Environment.NewLine + errorLog.ToString() + Environment.NewLine + "Echoes";
        IsWorking = false;
    }

    private void ParseElement(JsonElement element, StringBuilder sb, string indent)
    {
        foreach (var property in element.EnumerateObject())
        {
            if (property.Value.ValueKind == JsonValueKind.Object)
            {
                sb.AppendLine($"{indent}■ {property.Name.ToUpper()}:");
                ParseElement(property.Value, sb, indent + "  ");
            }
            else if (property.Value.ValueKind == JsonValueKind.Array)
            {
                sb.AppendLine($"{indent}■ {property.Name.ToUpper()}: {property.Value.GetRawText()}");
            }
            else
            {
                string key = property.Name.Replace("_", " ").PadRight(15);
                sb.AppendLine($"{indent}  {key} : {property.Value}");
            }
        }
    }
}