<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    
    <Version>0.2.2</Version>
    <AssemblyVersion>0.2.2.0</AssemblyVersion>
    <FileVersion>0.2.2.0</FileVersion>
    <Description>Small utilities for network, API, and string tasks; throwing packets from a distant time, just to see what comes willowing back across the sand.</Description>
    
    <ApplicationIcon>Assets\echoes.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    
  </PropertyGroup>

  <PropertyGroup>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <TrimMode>copyused</TrimMode>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.HtmlRenderer" Version="11.2.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="DnsClient" Version="1.8.0" />
    <PackageReference Include="SSH.NET" Version="2025.1.0" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Remove="Assets\echoes.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\workflows\release.yml" />
  </ItemGroup>
</Project>